//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingShapeWCFService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IShapeService")]
    public interface IShapeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShapeService/AreaOfCircle", ReplyAction="http://tempuri.org/IShapeService/AreaOfCircleResponse")]
        float AreaOfCircle(float radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShapeService/AreaOfCircle", ReplyAction="http://tempuri.org/IShapeService/AreaOfCircleResponse")]
        System.Threading.Tasks.Task<float> AreaOfCircleAsync(float radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShapeService/AreaOfRectangle", ReplyAction="http://tempuri.org/IShapeService/AreaOfRectangleResponse")]
        float AreaOfRectangle(float length, float breadth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShapeService/AreaOfRectangle", ReplyAction="http://tempuri.org/IShapeService/AreaOfRectangleResponse")]
        System.Threading.Tasks.Task<float> AreaOfRectangleAsync(float length, float breadth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShapeServiceChannel : UsingShapeWCFService.ServiceReference1.IShapeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShapeServiceClient : System.ServiceModel.ClientBase<UsingShapeWCFService.ServiceReference1.IShapeService>, UsingShapeWCFService.ServiceReference1.IShapeService {
        
        public ShapeServiceClient() {
        }
        
        public ShapeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShapeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float AreaOfCircle(float radius) {
            return base.Channel.AreaOfCircle(radius);
        }
        
        public System.Threading.Tasks.Task<float> AreaOfCircleAsync(float radius) {
            return base.Channel.AreaOfCircleAsync(radius);
        }
        
        public float AreaOfRectangle(float length, float breadth) {
            return base.Channel.AreaOfRectangle(length, breadth);
        }
        
        public System.Threading.Tasks.Task<float> AreaOfRectangleAsync(float length, float breadth) {
            return base.Channel.AreaOfRectangleAsync(length, breadth);
        }
    }
}
